language: ruby
rvm: 2.2.0
sudo: false
cache:
- bundler
bundler_args: "--without production development"
branches:
  only:
  - master
before_script:
- npm install -g bower
- bower install
- bundle exec rake db:setup
deploy:
  provider: heroku
  app: h0printer
  skip_cleanup: true
  api_key:
    secure: fQmJurzR1ZNMEYUsMa31g/EGxDOPOwIt3pAayc8E6ZeiEpIPaRxoJF3LZcGFbdsIesDSwUYQx/+/dCafWdHInworJy9oVmPm+jgjE2GNdote9sBPAPAKJM4IogiXGd28FDSCNWL1pDqUloA23HOtf4drYHI6Wb0zg8N7uayHriJFWa4Auy1znT0bLiZDrLmieYDfLg/AQlfdVKjp71pm9x+LE5NGQaGwF9GXa3MHKaQCixGJtfBc+GrbJNBPsDBVJnlbu6DdZtMkT19Laaz/HgP9+JiPiqmwE55RHQpwtc41HFnICGTzvMFs62VOQlQvhxBm16Otuv2UAkZJaJdB8tik4DZsZh7u51kWNnf5l6buR1wCY3XLzCP0JXbl1JupzBV+yNbFkFjuMICEM086aE33IhuThZQjeWSXDW7SFSotJnKwUBSaKQju/V3aEKJCizdAwzuSZi1/474YXUBxUDkpW6cGMVBKiWr23OWbtdu6GHOkHkhOzc1lbIYjmNnDfTdX7GER/4W/gksQwoCvmx9PDszCzxaYrSwWpGJstJuCC4wT+X2/CEGWyJ4SqNWnNqTk1wFLAXMeTjj1cTvZs3E+puXXan4hAO/42vHYAlkOLgAR12OCWibe/RDoza1ec47DPzzEYKmqFKKJXkhGSzhExyu+QPMlO2Yc2Xm9wOU=
  run:
  - rake db:migrate
